ld:
  host: 127.0.0.1
  mysql-port: 3306
  nacos-port: 8848
  redis-port: 6379
  rocketmq-port:
  druid_password:          #durid控制台登陆密码
  mq-host1:
  mq-post1:
  mq-host2:
  mq-post2:
#nacos
nacos:
  #dev
  namespace: 79622650-2ad0-4651-945e-82929157836f
#database
DB_HOST: ${ld.host}:${ld.mysql-port}
DB_NAME: luck_draw
DB_USERNAME: root
DB_PASSWORD: ENC(m+MdesgvfhecR2Y2Imf5wy9kDjPAZSmlYvLYU3P7GJbAUHI/tTEQo1HI5NbDv4Jn)

MQ_NAME_SERVER: ${ld.mq-host1}:${ld.mq-port1};${ld.mq-host2}:${ld.mq-port2}
MQ_GROUP: lucky-draw