ld:
  host: 127.0.0.1
  mysql-port: 3306
  nacos-port: 8848
  redis-port: 6379
  rocketmq-port:
#nacos
nacos:
  #dev
  namespace: 79622650-2ad0-4651-945e-82929157836f
#database
DB_HOST: ${ld.host}:${ld.mysql-port}
DB_NAME: luck_draw
DB_USERNAME: root
DB_PASSWORD: zyl13636228564